name: APK

on:
  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 202505081
  BUILD_VERSION: 0.0.5
  PYTHON_VERSION: 3.13.1
  FLUTTER_VERSION: 3.29.3

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flet Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION --product "Cambio Actual" --org com.aewaredevs --no-android-splash

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk
        path: build/apk
        if-no-files-found: warn
        overwrite: false

  build-ipa:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flet Build IPA
      run: |
        flutter config --no-analytics
        flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION --product "Cambio Actual" --org com.aewaredevs

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ipa
        path: build/ipa
        if-no-files-found: warn
        overwrite: false

  build-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flet Build Windows
      run: |
        flutter config --no-analytics
        flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION --project "Cambio Actual" --product "Cambio Actual" --copyright "Copyright (c) 2024 AEwareDevs & ByteBloom"

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: windows
        path: build/windows
        if-no-files-found: warn
        overwrite: false

  create-release:
    needs: [build-apk, build-ipa, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} #GitHub Token
        with:
          tag_name: v${{ env.BUILD_VERSION }}
          release_name: v${{ env.BUILD_VERSION }}
          draft: false
          prerelease: false

      - name: Zip Artifacts
        run: |
          cd artifacts
          echo "Initial directory structure:"
          ls -la
          echo "\nShowing ipa contents:"
          ls -la ipa/
          echo "\nShowing complete path structure:"
          find ipa -type d
          mv ipa/Runner.xcarchive/Products/Applications ipa/Payload
          echo "\nDirectory structure after mv:"
          ls -la ipa/
          cd ipa
          zip -r ../ipa.ipa Payload
          cd ..
          zip -r windows-${{ env.BUILD_VERSION }}-amd64.zip windows/

      - name: List Workspace After Zipping
        run: |
          echo "Artifacts Directory After Zipping:"
          ls -la artifacts/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ls -la artifacts/
            artifacts/apk/app-release.apk
            artifacts/ipa.ipa
            artifacts/windows-${{ env.BUILD_VERSION }}-amd64.zip
          tag_name: v${{ env.BUILD_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} #GitHub Token